/** Passive identity-directory contracts. No credentials or authentication secrets. */
export type {
  IdentityCreateGroupFromTemplateRequest,
  IdentityCreateGroupRequest,
  IdentityCreateTenantMembershipRequest,
  IdentityCreateTenantRequest,
  IdentityCreateUserRequest,
  IdentityGroupMemberRecord,
  IdentityGroupRecord,
  IdentityGroupStatus,
  IdentityGroupTemplateResourceScopeMapping,
  IdentityGroupTemplateResourceScopeRequirement,
  IdentityMembershipStatus,
  IdentityTenantMembershipRecord,
  IdentityTenantRecord,
  IdentityTenantStatus,
  IdentityTenantUserRecord,
  IdentityTenantUserListOptions,
  IdentityUpdateGroupRequest,
  IdentityUpdateTenantMembershipRequest,
  IdentityUpdateTenantRequest,
  IdentityUpdateUserRequest,
  IdentityUserRecord,
  IdentityUserStatus,
} from "@identity-access/client";
