import type { ReactNode } from "react";
import type { IdentityScopeAuthorityGroupRecord, IdentityScopeAuthorityMemberRecord, IdentityScopeAuthorityPolicyBindingRecord, IdentityScopeAuthorityPolicyRecord } from "@generic-identity/contracts/access-control";
import { IdentityEmptyState, IdentityPageFrame, IdentityPanel, IdentityTable } from "../components/index";
import { activeStatus } from "./internal";
export interface DelegatedAuthorityPageProps { readonly groups: readonly IdentityScopeAuthorityGroupRecord[]; readonly policies: readonly IdentityScopeAuthorityPolicyRecord[]; readonly members?: readonly IdentityScopeAuthorityMemberRecord[]; readonly bindings?: readonly IdentityScopeAuthorityPolicyBindingRecord[]; readonly actions?: ReactNode; }
export function DelegatedAuthorityPage({ groups, policies, members = [], bindings = [], actions }: DelegatedAuthorityPageProps) {
  return <IdentityPageFrame title="Delegated authority" description="Identity-scope administration groups, policies, memberships and bindings." actions={actions}>
    <IdentityPanel title="Authority groups">{groups.length === 0 ? <IdentityEmptyState title="No authority groups" /> : <IdentityTable caption="Authority groups"><thead><tr><th scope="col">Name</th><th scope="col">Group ID</th><th scope="col">Status</th><th scope="col">Version</th></tr></thead><tbody>{groups.map((group) => <tr key={group.groupId}><td>{group.displayName}</td><td><code>{group.groupId}</code></td><td>{activeStatus(group.status)}</td><td>{group.version}</td></tr>)}</tbody></IdentityTable>}</IdentityPanel>
    <IdentityPanel title="Authority policies">{policies.length === 0 ? <IdentityEmptyState title="No authority policies" /> : <IdentityTable caption="Authority policies"><thead><tr><th scope="col">Name</th><th scope="col">Policy ID</th><th scope="col">Status</th><th scope="col">Version</th></tr></thead><tbody>{policies.map((policy) => <tr key={policy.policyId}><td>{policy.displayName}</td><td><code>{policy.policyId}</code></td><td>{activeStatus(policy.status)}</td><td>{policy.version}</td></tr>)}</tbody></IdentityTable>}</IdentityPanel>
    <IdentityPanel title="Selected memberships and bindings">{members.length === 0 && bindings.length === 0 ? <IdentityEmptyState title="No selected authority relationships" /> : <IdentityTable caption="Authority relationships"><thead><tr><th scope="col">Kind</th><th scope="col">Group ID</th><th scope="col">Target</th></tr></thead><tbody>{members.map((member) => <tr key={`member:${member.groupId}:${member.userId}`}><td>Member</td><td><code>{member.groupId}</code></td><td><code>{member.userId}</code></td></tr>)}{bindings.map((binding) => <tr key={`binding:${binding.groupId}:${binding.policyId}`}><td>Policy binding</td><td><code>{binding.groupId}</code></td><td><code>{binding.policyId}</code></td></tr>)}</tbody></IdentityTable>}</IdentityPanel>
  </IdentityPageFrame>;
}
