import type { ReactNode } from "react";
import type { IdentityGroupMemberRecord, IdentityGroupRecord, IdentityManagedGroupPolicyBindingRecord } from "@generic-identity/contracts/access-control";
import { IdentityEmptyState, IdentityPageFrame, IdentityPanel, IdentityTable } from "../components/index";
import { activeStatus } from "./internal";
export interface GroupAccessPageProps { readonly group: IdentityGroupRecord; readonly members?: readonly IdentityGroupMemberRecord[]; readonly managedPolicyBindings?: readonly IdentityManagedGroupPolicyBindingRecord[]; readonly actions?: ReactNode; readonly memberActions?: ReactNode; readonly policyBindingActions?: ReactNode; }
export function GroupAccessPage({ group, members = [], managedPolicyBindings = [], actions, memberActions, policyBindingActions }: GroupAccessPageProps) {
  return <IdentityPageFrame title={group.displayName} description={`Access control group ${group.groupId}`} actions={actions}>
    <IdentityPanel title="Group"><dl className="gi-definition-list"><div><dt>Tenant</dt><dd><code>{group.tenantId}</code></dd></div><div><dt>Status</dt><dd>{activeStatus(group.status)}</dd></div><div><dt>Template</dt><dd>{group.isTemplate ? "Yes" : "No"}</dd></div><div><dt>Version</dt><dd>{group.version}</dd></div></dl></IdentityPanel>
    <IdentityPanel title="Members">{memberActions ? <div className="gi-panel-actions">{memberActions}</div> : null}{members.length === 0 ? <IdentityEmptyState title="No members" /> : <IdentityTable caption="Group members"><thead><tr><th scope="col">User ID</th><th scope="col">Tenant membership ID</th></tr></thead><tbody>{members.map((member) => <tr key={member.tenantMembershipId}><td><code>{member.userId}</code></td><td><code>{member.tenantMembershipId}</code></td></tr>)}</tbody></IdentityTable>}</IdentityPanel>
    <IdentityPanel title="Policy bindings">{policyBindingActions ? <div className="gi-panel-actions">{policyBindingActions}</div> : null}{managedPolicyBindings.length === 0 ? <IdentityEmptyState title="No policy bindings" /> : <IdentityTable caption="Group policy bindings"><thead><tr><th scope="col">Policy ID</th><th scope="col">Version</th><th scope="col">Resource scope</th><th scope="col">Descendants</th></tr></thead><tbody>{managedPolicyBindings.map((binding) => <tr key={`managed:${binding.policyId}:${binding.policyVersion}:${binding.resourceScopeId ?? ""}`}><td><code>{binding.policyId}</code></td><td>{binding.policyVersion}</td><td>{binding.resourceScopeId ? <code>{binding.resourceScopeId}</code> : "Unscoped"}</td><td>{binding.includeDescendants ? "Yes" : "No"}</td></tr>)}</tbody></IdentityTable>}</IdentityPanel>
  </IdentityPageFrame>;
}
