/** Generic Access Control contracts exposed through the shared SDK. */
export type {
  IdentityAddManagedGroupPolicyBindingRequest,
  IdentityAddManagedPolicyStatementRequest,
  IdentityAddPolicyStatementRequest,
  IdentityAdministrationListOptions,
  IdentityCreateGroupFromTemplateRequest,
  IdentityCreateGroupRequest,
  IdentityCreateManagedPolicyRequest,
  IdentityCreateManagedPolicyVersionRequest,
  IdentityCreatePolicyRequest,
  IdentityCreateResourceScopeRequest,
  IdentityGroupMemberRecord,
  IdentityGroupRecord,
  IdentityGroupStatus,
  IdentityGroupTemplateResourceScopeMapping,
  IdentityGroupTemplateResourceScopeRequirement,
  IdentityManagedGroupPolicyBindingRecord,
  IdentityManagedPolicyRecord,
  IdentityManagedPolicyStatementRecord,
  IdentityManagedPolicyVersionRecord,
  IdentityPublishManagedPolicyVersionRequest,
  IdentityResourceScopeRecord,
  IdentityResourceScopeStatus,
  IdentityScopeAuthorityGroupRecord,
  IdentityScopeAuthorityMemberRecord,
  IdentityScopeAuthorityPolicyBindingRecord,
  IdentityScopeAuthorityPolicyRecord,
  IdentityScopeAuthorityPolicyStatementRecord,
  IdentityUpdateGroupRequest,
  IdentityUpdateManagedPolicyRequest,
  IdentityUpdatePolicyRequest,
  IdentityUpdateResourceScopeRequest,
  IdentityUpdateReusableGroupRequest,
} from "@identity-access/client";
